name 'fuin-puppet-eclipse'
version '0.1.0'

author 'Michael Schnell, Roman Voitenko'
license 'Apache 2.0'
project_page 'https://github.com/michael-schnell/fuin-puppet-eclipse'
source 'https://github.com/michael-schnell/fuin-puppet-eclipse.git'
summary 'Manage Eclipse installation with Puppet'
description 'Download and install Eclipse with Puppet.'
dependency 'puppet-archive', '>=0.1.1'
